### ISSUE TITLE
Add slides from Workshops

### ISSUE THREAD

**Issue by suranc** [githubuniverseworkshops/the-metrics-that-matter#4]
During the workshops you said you would be adding the queries from the slides.  Could you commit those, or update the README to link to them?

**Comment by stoe** [comment]
@suranc, please apologize the long silence.

The slides are available in this repo here via 
https://github.com/universeworkshops/the-metrics-that-matter/blob/master/the-metrics-that-matter.pdf

**Comment by suranc** [comment]
Got them, thanks!
